#!/bin/bash
#
# Example f5gs pre state change script.
# Usually found from path: /etc/f5gs/pre
#
# Sami Kerola <kerolasa@iki.fi>

# Uncomment if you need to debug.
#set -x
# Uncomment if you want to get rid of all output.
#exec > /dev/null 2>&1

# Default settings.
SCRIPT_INVOCATION_SHORT_NAME="${0##*/}"
set -e # exit on errors
# trap ERR is bashism, do not change shebang!
trap 'echo "${SCRIPT_INVOCATION_SHORT_NAME}: exit on error" >&2; exit 1' ERR
set -C # disallow redirection overwrites
set -u # disallow usage of unset variables
set -o pipefail # make pipe writer failure to cause exit on error

F5GS_REQUESTED_STATE='dummyvalue'
F5GS_LISTEN='0.0.0.0'
F5GS_PORT='32546'
#F5GS_STATEDIR='/var/run/f5gs'
RETVAL=0

msg() {
	echo "${SCRIPT_INVOCATION_SHORT_NAME}: ${@}" >&2
}

usage() {
	echo "Usage: $0 [options]"
	echo 'See options from: f5gs --help'
	exit 1
}

OPTION_DEFINITION=$(
	getopt -o dmesl:p:hV \
		-l disable,maintenance,enable,server,listen:,port:,state:,help,version \
		-n "$SCRIPT_INVOCATION_SHORT_NAME" -- "$@"
)

eval set -- "$OPTION_DEFINITION"

while : ; do
	case "$1" in
		-d|--disable)
			F5GS_REQUESTED_STATE='disable'
			shift
			;;
		-m|--maintenance)
			F5GS_REQUESTED_STATE='maintenance'
			shift
			;;
		-e|--enable)
			F5GS_REQUESTED_STATE='enable'
			shift
			;;
		-s|--server)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		-l|--listen)
			F5GS_LISTEN=$(getent hosts "$2" | awk '{print $1; exit 0}')
			shift 2
			;;
		-p|--port)
			F5GS_PORT="$2"
			shift 2
			;;
		--state)
			# ignored for now, maybe there is a use for the
			# value in future.  please send a patch if so.
			#F5GS_STATEDIR="$2"
			shift 2
			;;
		-h|--help)
			# this should be impossible, but ignore just in
			# case.
			usage
			shift
			;;
		-V|--version)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		--)
			# see 'man getopt' why
			shift
			break
			;;
		*)
			# this should be impossible
			exit 1
			shift
			;;
	esac
done
# All command line option related stuff is done.

CURRENT_STATE=$(f5gs --listen $F5GS_LISTEN --port $F5GS_PORT | sed 's/^current status is: //')
if [ "$CURRENT_STATE" = "$F5GS_REQUESTED_STATE" ]; then
	msg 'requested state is same as run state'
	exit 1
fi

set_iptables_rules() {
	trap 'return 1' ERR
	iptables -A INPUT -m pkttype --pkt-type multicast -j DROP
	iptables -A OUTPUT -m pkttype --pkt-type multicast -j DROP
	return 0
}

remove_iptables_rules() {
	trap 'return 1' ERR
	iptables -D INPUT -m pkttype --pkt-type multicast -j DROP
	iptables -D OUTPUT -m pkttype --pkt-type multicast -j DROP
	return 0
}

# What should be done.
case "$CURRENT_STATE:$F5GS_REQUESTED_STATE" in
	'unknown:enable'|'maintenance:disable'|'disable:maintenance')
		: # do nothing
		;;
	'enable:maintenance'|'enable:disable'|'unknown:disable'|'unknown:maintenance')
		set_iptables_rules
		;;
	'disable:enable'|'maintenance:enable')
		remove_iptables_rules
		;;
	*)
		msg 'was this script ran by manually without state option?'
		RETVAL=42
		;;
esac

exit $RETVAL
# EOF
