#!/bin/bash
#
# Example f5gs pre state change script.
# Usually found from path: /etc/f5gs/pre
#
# Sami Kerola <kerolasa@iki.fi>

# Uncomment if you need to debug.
#set -x
# Uncomment if you want to get rid of all output.
#exec > /dev/null 2>&1

# Default settings.
SCRIPT_INVOCATION_SHORT_NAME="${0##*/}"
set -e # exit on errors
# trap ERR is bashism, do not change shebang!
trap 'echo "${SCRIPT_INVOCATION_SHORT_NAME}: exit on error in line $LINENO" >&2; exit 1' ERR
set -C # disallow redirection overwrites
set -u # disallow usage of unset variables
set -o pipefail # make pipe writer failure to cause exit on error

F5GS_REQUESTED_STATE='dummyvalue'
F5GS_LISTEN='0.0.0.0'
F5GS_PORT='32546'
#F5GS_STATEDIR='/var/lib/f5gs'
RETVAL=0

msg() {
	echo "${SCRIPT_INVOCATION_SHORT_NAME}: ${@}" >&2
}

usage() {
	echo "Usage: $0 [options]"
	echo 'See options from: f5gs --help'
	exit 1
}

OPTION_DEFINITION=$(
	getopt -o dmesa:p:qhV \
		-l disable,maintenance,enable,server,address:,port:,statedir:,quiet,reason:,why,no-script,foreground,help,version \
		-n "$SCRIPT_INVOCATION_SHORT_NAME" -- "$@"
)

eval set -- "$OPTION_DEFINITION"

while : ; do
	case "$1" in
		-d|--disable)
			F5GS_REQUESTED_STATE='disable'
			shift
			;;
		-m|--maintenance)
			F5GS_REQUESTED_STATE='maintenance'
			shift
			;;
		-e|--enable)
			F5GS_REQUESTED_STATE='enable'
			shift
			;;
		-s|--server)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		-a|--address)
			F5GS_LISTEN=$(getent hosts "$2" | awk '{print $1; exit 0}')
			shift 2
			;;
		-p|--port)
			F5GS_PORT="$2"
			shift 2
			;;
		--statedir)
			# ignored for now, maybe there is a use for the
			# value in future.  please send a patch if so.
			#F5GS_STATEDIR="$2"
			shift 2
			;;
		-q|--quiet)
			# ignored for now, maybe there is a use for the
			# value in future.  please send a patch if so.
			shift
			;;
		--reason)
			# ignored for now, maybe there is a use for the
			# value in future.  please send a patch if so.
			shift 2
			;;
		--why)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		--no-script)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		--foreground)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		-h|--help)
			# this should be impossible, but ignore just in
			# case.
			usage
			shift
			;;
		-V|--version)
			# this should be impossible, but ignore just in
			# case.
			shift
			;;
		--)
			# see 'man getopt' why
			shift
			break
			;;
		*)
			# this should be impossible
			exit 1
			shift
			;;
	esac
done
# All command line option related stuff is done.

CURRENT_STATE=$(f5gs --address $F5GS_LISTEN --port $F5GS_PORT | sed 's/.*current status is: //')
if [ "$CURRENT_STATE" = "$F5GS_REQUESTED_STATE" ]; then
	msg 'requested state is same as run state'
	exit 1
fi

iptables_rules() {
	trap 'return 1' ERR
	iptables $1 INPUT -m pkttype --pkt-type multicast -j DROP
	iptables $1 OUTPUT -m pkttype --pkt-type multicast -j DROP
	if [ -x /etc/init.d/iptables ]; then
		/etc/init.d/iptables save >/dev/null 2>&1
	fi
	return 0
}

# What should be done.
case "$CURRENT_STATE:$F5GS_REQUESTED_STATE" in
	'unknown:enable'|'maintenance:disable'|'disable:maintenance')
		: # do nothing
		;;
	'enable:maintenance'|'enable:disable'|'unknown:disable'|'unknown:maintenance')
		iptables_rules -A
		;;
	'disable:enable'|'maintenance:enable')
		iptables_rules -D
		;;
	*)
		msg 'was this script ran manually without state change option?'
		RETVAL=42
		;;
esac

exit $RETVAL
# EOF
