#!/bin/bash

. "${srcdir=.}/tests/init.sh"
retval=0
rm -f ./$testname.{exp,out} "$state_dir/127.0.0.1:$tcp_port"

cat >./$testname.exp <<END
127.0.0.1: current status is: enable
127.0.0.1: current status is: enable
127.0.0.1: current status is: enable
testdir/127.0.0.1:19862
127.0.0.1: current status is: enable
END

f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --server >> ./$testname.out 2>&1
f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --enable --force --reason "abc 123 xyz" >> ./$testname.out 2>&1
f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --no-scripts >> ./$testname.out 2>&1
read -ra state_array < "$state_dir/127.0.0.1:$tcp_port"
kill -TERM ${state_array[0]}

f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --server >> ./$testname.out 2>&1
f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --no-scripts >> ./$testname.out 2>&1
read -ra state_array < "$state_dir/127.0.0.1:$tcp_port"
rm -f "$state_dir/127.0.0.1:$tcp_port"
kill -HUP ${state_array[0]}
sleep 0.1
ls "$state_dir/127.0.0.1:$tcp_port" 2>&1 | sed "s|$state_dir|testdir|" >> ./$testname.out

f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --server >> ./$testname.out 2>&1
f5gs --address 127.0.0.1 --port $tcp_port --statedir "$state_dir" --no-scripts >> ./$testname.out 2>&1
read -ra state_array < "$state_dir/127.0.0.1:$tcp_port"
kill -USR1 ${state_array[0]}

diff -u ./$testname.{exp,out}
if [ $? -ne 0 ]; then retval=1; fi
rm -f ./$testname.{exp,out} "$state_dir/127.0.0.1:$tcp_port"

exit $retval
